/**
 * Generates DOCUMENTATION.pdf (requires: npm install)
 */
const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

const outPath = path.join(__dirname, 'DOCUMENTATION.pdf');
const doc = new PDFDocument({ size: 'A4', margins: { top: 50, bottom: 50, left: 56, right: 56 } });
doc.pipe(fs.createWriteStream(outPath));

const ghUser = 'jeremiahayisi1234-ops';
const ghRepo = 'Examination';
const ghRepoUrl = `https://github.com/${ghUser}/${ghRepo}`;
const ghPagesUrl = `https://${ghUser}.github.io/${ghRepo}/`;

doc.fontSize(18).text('Luxury Villa VR (A-Frame)', { underline: true });
doc.moveDown(0.5);
doc.fontSize(11).fillColor('#333').text('Examination — Design & implementation report');
doc.moveDown(1.2);

doc.fontSize(12).fillColor('#000').text('Repository (GitHub)', { underline: true });
doc.fontSize(10).text(`Clone: git clone ${ghRepoUrl}.git`);
doc.text(`Web UI: ${ghRepoUrl}`);
doc.text(`GitHub Pages (after enabling): ${ghPagesUrl}`);
doc.moveDown(0.8);

doc.fontSize(12).text('Course / school deployment', { underline: true });
doc.fontSize(10).text('Replace IndexNumber with your index:');
doc.text('https://IndexNumber.ceiscy.com/Examination', { link: 'https://IndexNumber.ceiscy.com/Examination' });
doc.moveDown(0.8);

doc.fontSize(12).text('1. Design goals', { underline: true });
doc.fontSize(10).text(
  'The project delivers a single-page WebVR luxury villa with six fully furnished rooms (two living rooms, two bedrooms, one kitchen, one dining area), exterior landscaping, a shader-animated swimming pool, nine trees in three species, and two children with a dog animated near the pool. Procedural primitives keep load times short and frame rates stable; lighting combines ambient, directional (sun with shadows), and localized point lights.'
);
doc.moveDown(0.6);

doc.fontSize(12).text('2. Layout & proportions', { underline: true });
doc.fontSize(10).text(
  'Approximate footprint 20 m × 14 m, ceiling height ~3 m. Front row (toward the garden/pool): Living room 1, Kitchen, Dining. Back row: Living room 2, Bedroom 1, Bedroom 2. Interior partitions at X = ±3 m and Z = 0 m define six cells with open thresholds for comfortable VR movement.'
);
doc.moveDown(0.6);

doc.fontSize(12).text('3. Implementation', { underline: true });
doc.fontSize(10).text('• A-Frame 1.4.2 (CDN).');
doc.text('• luxury-water: custom vertex/fragment shader for moving pool surface (js/water-shader.js).');
doc.text('• pool-orbit / pool-zigzag: analytic motion for children and dog (js/pool-orbit.js).');
doc.text('• Tree factories for pine, round, and palm types — three instances each (js/scene-helpers.js).');
doc.text('• Optional procedural canvas textures for wood/marble/grass (js/procedural-textures.js).');
doc.moveDown(0.6);

doc.fontSize(12).text('4. Lighting', { underline: true });
doc.fontSize(10).text(
  'Ambient fill, one directional sun with PCF soft shadows, and point lights per room zone plus pool deck. Intensities and decay tuned so interiors read clearly without blowing out the exterior.'
);
doc.moveDown(0.6);

doc.fontSize(12).text('5. Performance', { underline: true });
doc.fontSize(10).text(
  'No heavy external meshes on first paint; primitives only. Shadows limited to meaningful objects; water does not cast shadows. Renderer uses colour management and physically correct lights. Canvas textures are small (256×256) and reused where possible.'
);
doc.moveDown(0.6);

doc.fontSize(12).text('6. Challenges & solutions', { underline: true });
doc.fontSize(10).text('• Water shader before mesh ready → wait for object3dset, then attach ShaderMaterial.');
doc.text('• Circular paths without keyframe assets → pool-orbit / pool-zigzag components.');
doc.text('• Nine trees without nine files → factory functions + data-tree markers in HTML.');
doc.text('• GitHub Pages: push repository, Settings → Pages → branch main / root or /docs (see README).');
doc.moveDown(0.8);

doc.fontSize(12).text('7. File layout', { underline: true });
doc.fontSize(9).font('Courier');
doc.text('Examination/\n  index.html\n  js/\n    water-shader.js\n    pool-orbit.js\n    scene-helpers.js\n    procedural-textures.js\n  DOCUMENTATION.pdf (this file)\n  DOCUMENTATION.md / DOCUMENTATION.html\n  README.md\n  package.json / gen-pdf.js');
doc.font('Helvetica');
doc.moveDown(0.8);

doc.fontSize(10).fillColor('#666').text('Generated by gen-pdf.js — run: npm install && npm run doc-pdf', { align: 'right' });

doc.end();
console.log('Wrote:', outPath);
